### PR TITLE
WIP: Add pyproject with setup.py imports for better pip ergonomics

### PR DESCRIPTION
**Pull request by kdm9**
While not strictly required, listing the 'setup_requires' dependencies in a `pyprojects.toml` makes installing from git/zip files a lot easier with modern pip and build tools.

(e.g., compare `python3 -m build --wheel` run before and after this change)

### CODE REVIEW

**Comment by kdm9** [comment]
fyi @kcleal trying to get htslib to correctly detect libbz2, which would upload a wheel nicely as part of the CI, so I can install direct from a wheel.

**Comment by kcleal** [comment]
Hi @kdm9,
The workflow seems to break at regular intervals. Im trying to get it sorted also in the dysgu_dev branch. The ubuntu workflow was working yesterday using this workflow: https://github.com/kcleal/dysgu/actions/runs/9927148538/workflow

Currently stuck getting macos to build

**Comment by kcleal** [comment]
> fyi @kcleal trying to get htslib to correctly detect libbz2, which would upload a wheel nicely as part of the CI, so I can install direct from a wheel.

I think ubuntu needs to be ubuntu-latest now, otherwise the yum package manager breaks

**Comment by kcleal** [comment]
I added a pyproject.toml as you suggested and it looks like the macos workflow is now working. Thanks!

https://github.com/kcleal/dysgu/actions/runs/9938165730/job/27450040742

**Comment by kcleal** [comment]
Hi @kdm9,
I have now implemented some of these changes in the main branch. Would you be able to take a look and see if there is anything else you would like to add? Thanks for the input, it is much appreciated.
Kez

**Comment by kdm9** [comment]
just confirmed that this all seems to be working OK, so I'll close this

**Pull request closed without merging**
