### PR TITLE
Dysgy v1.6.4

### PR DESCRIPTION
**Pull request by kcleal**
v1.6.4
====
Minor update adding following features and fixes
- Faster --cohort-update option for dysgu merge
- Returns an empty vcf file (with header) when no events called
- Merged #89 thanks to @JMencius checks for sorted input where possible
- Small speed increase

### CODE REVIEW

**Comment by poddarharsh15** [comment]
Hi @kcleal is it possible to possible to pull this branch to test the `Returns an empty vcf file (with header) when no events called` 
Please let me know, Thanks :)

**Comment by kcleal** [comment]
Hi @poddarharsh15,
Yes it is more or less ready for release. I just need to run some validation tests, but there will probably be no changes needed

**Comment by poddarharsh15** [comment]
Okay I will wait for your release and later I will add latest version as module, Thanks again:)

**Comment by JMencius** [comment]
Hi @kcleal @poddarharsh15  I can deal with this request later if you want and create a PR.

**Comment by poddarharsh15** [comment]
Hi @kcleal did you make any updates?

**Pull request merged**
